import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserDiaryProvider from "@/provider/userDiaryProvider";
import { Toaster } from "sonner";
import UserContextProvider from "@/provider/userProvider";
import { ThemeInitializer } from "@/provider/ThemeInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased my-bg`}
      >
        <UserContextProvider>
          <UserDiaryProvider>
            <ThemeInitializer />
            <main>{children}</main>
            <Toaster
              richColors
              position="top-center"
              toastOptions={{
                style: { zIndex: 99999 },
              }}
            />
          </UserDiaryProvider>
        </UserContextProvider>
      </body>
    </html>
  );
}
